# Generated by Django 4.0.6 on 2022-07-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='cat_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='pro_slug',
        ),
    ]
