# Generated by Django 4.1 on 2022-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceA', '0009_category_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
